services:
  - type: web
    name: ihatepdf
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: RENDER_EXTERNAL_URL
        value: https://ihatepdf.onrender.com
    healthCheckPath: /health
